spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/skarte
    username: skarte
    password: password
  h2:
    console:
      enabled: true
debug: true